name: EAS Build Framework

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK and iOS IPA
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm config set legacy-peer-deps true && npm ci

      - name: 🚀 Build Android APK
        run: eas build --platform android --profile preview --non-interactive

      - name: 🚀 Build iOS IPA
        run: eas build --platform ios --profile preview --non-interactive
